objects/MessagingSession.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Messaging Sessions</relationshipLabel>
        <relationshipName>Messaging_Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AuthSessionId__c</fullName>
        <label>AuthSessionId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ContactId</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Messaging Sessions</relationshipLabel>
        <relationshipName>Messaging_Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MessagingSessionUpdater.cls
public with sharing class MessagingSessionUpdater {
    @AuraEnabled
    public static void updateAuthSession(String sessionKey) {
        // Fetch the active messaging session
        MessagingSession ms = MessagingSessionService.getActiveSession(sessionKey);
        if (ms != null) {
            // Retrieve current session ID
            String sessionId = Auth.SessionManagement.getCurrentSession().get('SessionId');

            // Fetch user details
            User authUser = [
                SELECT Id, ContactId, AccountId FROM User WHERE Id = :UserInfo.getUserId()
            ];

            // Update MessagingSession fields
            ms.AuthSessionId__c = sessionId;
            ms.AccountId__c = authUser.AccountId;
            ms.ContactId__c = authUser.ContactId;

            update ms;
        }
    }
}